### PR TITLE
#55: Player can choose a deck to play (AI will choose randomly from t…

### PR DESCRIPTION
**Pull request by cclp94**
…he remaining decks: supports mutiple decks)

### CODE REVIEW

**Review by DrunkDutch — CHANGES_REQUESTED** [review]
Game is throwing the following exception for me on startup, in regards to attempting to iterate over the deck lists in the deck folder:
Exception in thread "main" java.lang.NullPointerException
	at com.dmens.pokeno.Driver.GameController.chooseDeck(GameController.java:230)
	at com.dmens.pokeno.Driver.GameController.main(GameController.java:57)

**Comment by cclp94** [comment]
@DrunkDutch Can't reproduce the Exception. WHere you running the jar or through the IDE? Did you refresh the files so the file folder could be updated in the IDE?

**Comment by DrunkDutch** [comment]
Running it via the jar, with a full maven clean package . Via the IDE it works fine, i'll take a look into it later this weekend, might be due to how the new file location is handled by the packager

**Comment by DrunkDutch** [comment]
Taking ownership of this PR to fix the issues I raised

**Review by DrunkDutch — APPROVED** [review]

**Comment by cclp94** [comment]
@DrunkDutch Now for me it runs fine on the jar but nothing gets shown when running with the IDE

**Comment by DrunkDutch** [comment]
I'll look into getting it to work for both right now

**Pull request merged**
